PAIRV_SDK_LIB ?= $(NUCLEI_SDK_ROOT)/Lib
PAIRV_SDK_LIB_SRCS := $(sort $(wildcard $(PAIRV_SDK_LIB)/*.c))

include $(PAIRV_SDK_LIB)/runtime/build.mk

INCDIRS += $(PAIRV_SDK_LIB)
C_SRCDIRS += $(PAIRV_SDK_LIB)
C_SRCS += $(PAIRV_SDK_LIB_SRCS)
