RVRT_MAX_WORKSPACE_FRAMES ?= 512
RVRT_SESSION_ENABLE_STATS ?= 0

COMMON_FLAGS += -DRVRT_MAX_WORKSPACE_FRAMES=$(RVRT_MAX_WORKSPACE_FRAMES)
COMMON_FLAGS += -DRVRT_SESSION_ENABLE_STATS=$(RVRT_SESSION_ENABLE_STATS)
