#!/usr/bin/env python3
"""Generate snn_head_params.c from the INT8 QAT export-state package.

CPU-side operators (LayerNorm / quantize / dequantize) need only:
  * LayerNorm weight/bias (4 sites, float32)
  * per-tensor activation_scale (5 linears, for the int8 quantize step)
  * per-output-channel output_scale for fc2 and fc3 (for the int32 -> fp32
    dequantize step); fc1/block0/block1 feed the brain-core LIF directly so
    their dequant lives in the PAICORE artifact, not on the CPU.

Everything is read straight from snn_head_int8_quant_export_state.pt, which
already stores the frozen quantization products. This script only reshapes them
into a C source that defines the extern symbols declared in
snn_head_internal.h. Re-run it whenever the export package is refreshed.
"""

from __future__ import annotations

import sys
from pathlib import Path

import torch

DEFAULT_PT = (
    "/mnt/work/linjiamu/VLA/snnhead_lif_rdfalse_int8qat_headonly_"
    "s1000_q9995_bc_20260701/snn_head_int8_quant_export_state.pt"
)
OUT_C = Path(__file__).resolve().parent / "snn_head_params.c"

# (C symbol, state-dict key, expected length or None for scalar)
LN_ARRAYS = [
    ("snn_head_ln1_weight", "model.layer_norm1.weight_float", 768),
    ("snn_head_ln1_bias", "model.layer_norm1.bias_float", 768),
    ("snn_head_block0_ln_weight", "model.mlp_resnet_blocks.0.ffn.0.weight_float", 1536),
    ("snn_head_block0_ln_bias", "model.mlp_resnet_blocks.0.ffn.0.bias_float", 1536),
    ("snn_head_block1_ln_weight", "model.mlp_resnet_blocks.1.ffn.0.weight_float", 1536),
    ("snn_head_block1_ln_bias", "model.mlp_resnet_blocks.1.ffn.0.bias_float", 1536),
    ("snn_head_ln2_weight", "model.layer_norm2.weight_float", 1536),
    ("snn_head_ln2_bias", "model.layer_norm2.bias_float", 1536),
]

SCALARS = [
    ("snn_head_fc1_activation_scale", "model.fc1.activation_scale"),
    ("snn_head_block0_activation_scale", "model.mlp_resnet_blocks.0.ffn.1.activation_scale"),
    ("snn_head_block1_activation_scale", "model.mlp_resnet_blocks.1.ffn.1.activation_scale"),
    ("snn_head_fc2_activation_scale", "model.fc2.activation_scale"),
    ("snn_head_fc3_activation_scale", "model.fc3.activation_scale"),
]

# output_scale = activation_scale * weight_scale (per output channel)
OUTPUT_SCALES = [
    ("snn_head_fc2_output_scale", "model.fc2", 1536),
    ("snn_head_fc3_output_scale", "model.fc3", 7),
]


def fmt_float(x: float) -> str:
    """Emit a float32-round-trip-exact C float literal (9 sig digits + 'f')."""
    v = float(torch.tensor(x, dtype=torch.float32).item())
    s = "%.9g" % v
    if ("." not in s) and ("e" not in s) and ("E" not in s) and ("inf" not in s) and ("nan" not in s):
        s += ".0"
    return s + "f"


def emit_array(name: str, dim_macro: str, values) -> str:
    lines = [f"const float {name}[{dim_macro}] SNN_HEAD_PARAM_DATA = {{"]
    row = []
    for i, v in enumerate(values):
        row.append(fmt_float(v))
        if len(row) == 8:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


def dim_macro_for(length: int) -> str:
    return {768: "SNN_HEAD_INPUT_DIM", 1536: "SNN_HEAD_HIDDEN_DIM", 7: "SNN_HEAD_ACTION_DIM"}[length]


def main() -> int:
    pt_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PT
    state = torch.load(pt_path, map_location="cpu", weights_only=False)

    out = []
    out.append("/*")
    out.append(" * AUTO-GENERATED by gen_snn_head_params.py -- DO NOT EDIT BY HAND.")
    out.append(f" * Source: {Path(pt_path).name}")
    out.append(" *")
    out.append(" * CPU-side SNN Head parameters (LayerNorm affine, activation_scale,")
    out.append(" * per-output-channel output_scale). All values are the frozen INT8 QAT")
    out.append(" * products; regenerate from the export package rather than editing here.")
    out.append(" */")
    out.append('#include "snn_head_internal.h"')
    out.append("")
    out.append("/* Large constants live in flash (.large_const_data), never in DLM/RAM. */")
    out.append("#define SNN_HEAD_PARAM_DATA "
               "__attribute__((section(\".large_const_data\"), aligned(8)))")
    out.append("")

    # LayerNorm affine arrays
    for name, key, length in LN_ARRAYS:
        t = state[key].detach().float().reshape(-1)
        assert t.numel() == length, f"{key}: {t.numel()} != {length}"
        out.append(emit_array(name, dim_macro_for(length), t.tolist()))
        out.append("")

    # Per-tensor activation scales
    for name, key in SCALARS:
        v = float(state[key].detach().float().reshape(()).item())
        out.append(f"const float {name} SNN_HEAD_PARAM_DATA = {fmt_float(v)};")
    out.append("")

    # Per-output-channel dequant scales (verify == act * weight_scale)
    for name, prefix, length in OUTPUT_SCALES:
        stored = state[f"{prefix}.output_scale"].detach().float().reshape(-1)
        act = state[f"{prefix}.activation_scale"].detach().float().reshape(())
        wsc = state[f"{prefix}.weight_scale"].detach().float().reshape(-1)
        recomputed = (act * wsc)
        max_diff = (stored - recomputed).abs().max().item()
        assert stored.numel() == length, f"{prefix}.output_scale: {stored.numel()} != {length}"
        assert max_diff < 1e-9, f"{prefix}: output_scale != act*weight_scale (max_diff={max_diff})"
        out.append(f"/* {prefix}.output_scale == activation_scale * weight_scale "
                   f"(verified max_diff={max_diff:.3e}) */")
        out.append(emit_array(name, dim_macro_for(length), stored.tolist()))
        out.append("")

    OUT_C.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT_C} ({len(out)} logical lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
