#ifndef __CPUFEATURE__
#define __CPUFEATURE__
#define CPU_ISA "rv32imac_zicsr_zicntr_zifencei_zicond_xxlnice"
#define CFG_CPU_NAME "n307"
#define CFG_CPU_VERSION "v4.11.0"
#define CFG_CPU_REV 0x40b00
#define CFG_E16 0
#define CFG_XLEN 32
#define CFG_HAS_ICACHE
#define CFG_BHT_GHR_W 8
#define CFG_PMP_GRAIN 0
#define CFG_IREGION_BASE_ADDR 0x18000000
#define CFG_REGNUM_IS_32
#define EVALSOC_SYSMEM_BASE 0x80000000
#define CFG_HAS_DEBUG_NEW
#define CFG_CACHEABLE_REGION_NUM 0
#define CFG_REGFILE_RST
#define CFG_HAS_MULDIV
#define CFG_MEM_TYPE_ICB
#define CFG_ICACHE_ADDR_WIDTH 13
#define EVALSOC_DRAM_RAM_DW 32
#define EVALSOC_DRAM_RAM_DP 32768
#define CFG_ILM_ADDR_WIDTH 17
#define CFG_HAS_DEVICE
#define EVALSOC_FLASH_XIP_BASE 0x20000000
#define EVALSOC_PERIPS_BASE 0x10000000
#define EVALSOC_DRAM_BASE_ADDR 0x68000000
#define CFG_HAS_NC
#define CFG_HAS_PREFETCH
#define CFG_HAS_NCDEV_REG
#define CFG_OITF_DEPTH_IS_6
#define EVALSOC_DRAM_WMSK_WIDTH 4
#define CFG_ILM_BASE_ADDR 0x80000000
#define CFG_DLM_ADDR_WIDTH 17
#define CFG_HAS_CACHE
#define EVALSOC_IRAM_ADDR_WIDTH 17
#define CFG_DEVICE_REGION0_MASK 0xff000000
#define CFG_ILM_ITF_TYPE_ICB
#define CFG_CPU_GEN_RTL_MODE part
#define CFG_MISALIGNED_ACCESS
#define CFG_ILM_DATA_WIDTH 32
#define EVALSOC_CFG_FLASH_XIP_BASE 0x20000000
#define CFG_NC_REGION0_BASE 0x30000000
#define EVALSOC_VERSION_IS_2
#define CFG_HAS_IOCC
#define CFG_LSU_ACCESS_ILM
#define CFG_HAS_DEBUG
#define EVALSOC_HAS_UART_MODEL
#define CFG_HAS_LBIU
#define CFG_HAS_REMAP 0
#define EVALSOC_CFG_SYSMEM_BASE 0x80000000
#define CFG_MEM_CUT_TIMING
#define EVALSOC_IRAM_RAM_AW 15
#define CFG_HAS_DLM
#define EVALSOC_IRAM_AW_LSB 2
#define CFG_BHT_ENTRY_WIDTH 7
#define CFG_CLIC_VERSION 1
#define EVALSOC_HAS_CPU_RAM_WRAPPER
#define CFG_CLIC_FLOP_OUT
#define CFG_HAS_ECLIC
#define CFG_HAS_BPU
#define CFG_DEDICATED_AGU
#define CFG_HAS_NICE
#define CFG_HAS_DEBUG13
#define CFG_CPU_IS_300
#define EVALSOC_CFG_SYSMEM_ADDR_WIDTH 28
#define EVALSOC_CFG_DRAM_BASE_ADDR 0x68000000
#define CFG_HAS_EXCP
#define EVALSOC_IRAM_BASE_ADDR 0x60000000
#define CFG_ADDR_SIZE_IS_32
#define CFG_DEVICE_REGION_NUM 1
#define CFG_CORE_PFX n307_
#define EVALSOC_SYSMEM_ADDR_WIDTH 28
#define EVALSOC_HAS_BIU2DLM
#define CFG_PMP_ENTRY_NUM 0
#define CFG_HAS_DEBUG_PRIVATE
#define CFG_HAS_LM 1
#define EVALSOC_CFG_IRAM_ADDR_WIDTH 15
#define EVALSOC_HAS_IRAM_DRAM
#define EVALSOC_DRAM_RAM_MW 4
#define CFG_HAS_AMO
#define EVALSOC_IRAM_WMSK_WIDTH 4
#define CFG_PC_HASH_WIDTH 7
#define CFG_REGFILE_2WP
#define CFG_HAS_RD_HI
#define CFG_TMR_BASE_ADDR 0x18030000
#define EVALSOC_DRAM_RAM_AW 15
#define EVALSOC_CFG_IRAM_BASE_ADDR 0x60000000
#define CFG_DEVICE_REGION0_BASE 0x10000000
#define CFG_DLM_BASE_ADDR 0x90000000
#define EVALSOC_FLASH_XIP_ADDR_WIDTH 28
#define CFG_HAS_CLIC
#define EVALSOC_HAS_SUBSYS_LM 1
#define CFG_HAS_DYNAMIC_BPU
#define CFG_NC_REGION0_MASK 0xffff0000
#define CFG_LSU_DW 32
#define CFG_HAS_PMONITOR
#define EVALSOC_IRAM_RAM_DW 32
#define CFG_DLM_ITF_TYPE_ICB
#define CFG_ILM_LATENCY 4
#define CFG_DEBUG_TRIGM_NUM 4
#define CFG_DEBUG_TAP_AON
#define CFG_INDEP_MULDIV
#define CFG_IFU_CUT_TIMING
#define CFG_PMA_CSR_NUM 2
#define EVALSOC_CFG_FLASH_XIP_ADDR_WIDTH 28
#define CFG_HAS_TRIGM
#define CFG_HAS_CLIC_EDGE
#define CFG_NC_REGION_NUM 1
#define EVALSOC_CFG_PERIPS_BASE 0x10000000
#define CFG_HAS_ZICOND_EXTENSION
#define CFG_IRQ_NUM 32
#define EVALSOC_IRAM_RAM_MW 4
#define EVALSOC_IRAM_DATA_WIDTH 32
#define EVALSOC_DRAM_ADDR_WIDTH 17
#define EVALSOC_IRAM_RAM_DP 32768
#define EVALSOC_DRAM_AW_LSB 2
#define CFG_TMR_PRIVATE
#define CFG_HAS_ASILB 0
#define CFG_CLICINTCTLBITS 3
#define CFG_PPI_ADDR_WIDTH 20
#define CFG_HAS_2_WIRE_DBG
#define CFG_HAS_PAIR_REGFILE
#define EVALSOC_DRAM_DATA_WIDTH 32
#define CFG_XLEN_IS_32
#define CFG_SYSMEM_DATA_WIDTH_IS_32
#define CFG_HAS_MEM_ITF
#define EVALSOC_HAS_BIU2ILM
#define CFG_HAS_NICE_CORE_DECODE
#define CFG_PPI_BASE_ADDR 0x10000000
#define CFG_HAS_ILM
#endif
